### ISSUE TITLE
Cocoapods crash on runtime

### ISSUE THREAD

**Issue by wgpsutherland** [thii/FontAwesome.swift#155]
Hi there, I am copying the details of the question I have asked in [this](https://stackoverflow.com/questions/46011572/fontawesome-swift-cocoapods-crash-on-runtime) stack overflow question.

I am attempting to use the library [thii/FontAwesome.swift][1] in my iOS project in XCode. I have been using it successfully by having the fontawesome library copied and pasted into my project, however I am now attempting to instead use the library through cocoapods, and am having problems.

I also use cocoapods successfully for Google admob, so the issue does not seem to be with my cocoapods installation.

Xcode is successfully indexing and seeing the fontawesome files, and as you can see in the following error it is managing to run the fontawesome code. The issue is that the `image` variable is an optional that is causing a crash when it is force unwrapped, as for some reason it is `nil`:

[![enter image description here][2]][2]

**Things I have tried:**

 - Cleaning the project
 - Cleaning the build folder
 - Emptying the derived data folder
 - Restarting xcode
 - Uninstalling the cocoapod library and reinstalling
 - Using a lower version of the cocoapod library

Thanks for any help you could give

  [1]: https://github.com/thii/FontAwesome.swift
  [2]: https://i.stack.imgur.com/iOsjY.jpg

**Comment by phoney** [comment]
What is your code that calls this method?

**Comment by OlafAndreas** [comment]
This function will always crash if you pass a size parameter that has a width or height value of `0`. This is because the `NSAttributedString` is never drawn to the image context since it has a size that doesn't fit any content.

One solution to fix this problem is to change the return type to `UIImage?` to mark it as an optional and remove the forced unwrap of `image`. This will have a huge impact on the projects using this pod today since it will break every line of code using this function.

Another solution is to clip the width and height to a minimum of 1. This will save the application from crashing, but is more a workaround than an actual fix.
