### ISSUE TITLE
Font Awesome 5 support

### ISSUE THREAD

**Issue by korbklein** [thii/FontAwesome.swift#176]
Font Awesome 5 is available! Please update your library

**Comment by ghowen** [comment]
@thii: Any plans on updating to FA 5? Love your library, so this would be greatly appreciated. Thanks!

**Comment by thii** [comment]
I guess updating the font file and the `FontAwesome` enum and it's done? A PR would be greatly appreciated.

**Comment by ghowen** [comment]
Yes and no :) FA 5 now has free, pro and brand icons. Also icons are available in solid, normal and light styles, making it 7 different fonts altogether.

**Comment by OlafAndreas** [comment]
I don't see any solution to supporting the pro version, my suggestion is to implement FA 5 free with solid, normal and light styles.

Pro version:
Since this cost 50$ per user, it doesn't make sense in serving the font via this pod. Maybe the font could be injected into the pod so that it can be used with the convenient wrapping this project provides.

Thoughts?

**Comment by ghowen** [comment]
It would probably also good to check in with the FA team. One of their Kickstarter goals was to support iOS and Android, although they did not specify in which way. Maybe they can support or sponsor this project? Last time I checked with them about this (about a month ago) Rob from FA said "It's on the list and we'll get to it as soon as we can."

**Comment by doedje** [comment]
I am a bit on the I-don't-know-side with FA5. Since it is a new design I wouldn't blindly replace the font in any of my projects with FA5. It does have a different look and feel to it. As a developer you should at least have the choice to stick with FA4 or go with FA5....

By the way, the free version of the font only supports the "solid" style, the normal and light styles are Pro icons. Which makes implementing FA5-Free quit easy actually....

**Comment by ghowen** [comment]
In 5.0.2 free there are 3 fonts: Free regular, Free solid and Brands Regular.

@doedje: If the support for FA5 is a major version bump of FontAwesome.swift, then you could still use the current version in the projects that need FA4. Would this work for you?

**Comment by doedje** [comment]
@ghowen: I would like to be able to switch to Swift5 when that comes.... so sticking to the current version is probably not an option.

**Comment by doedje** [comment]
I'll have a look at implementing FA5....

**Comment by OlafAndreas** [comment]
First of all I think the implementation of FA5 should be discussed, I've had a look at it yesterday and there are some issues that needs good solutions.

Here are my first thoughts.

#### Multiple fonts
We need to handle the loading of multiple fonts. Since FA5 Free is split into three different fonts, Regular, Solid and Regular_Brands, we should create a convenient way of loading and assigning the correct font according to what icon is being set.

#### Choosing style
When assigning an icon there should be an option to choose between regular and solid, regular could be chosen as default.

**Comment by ghowen** [comment]
If we implement multiple font support, it would be nice to at least consider support for the pro version of the fonts as well. Ideally you would just need to drop them into the project and the library would recognize them automatically. If you'd try to use a pro font without the font file present, the lib would either throw an error or return nil.

Another idea are presets for image sizes. These could be i.e. for toolbar items, standard buttons and tabbar items. We could also default here to the size that is felt to be most common (in my case images for UIBarButtonItems and UITableViewCells.

**Comment by EMakadiya** [comment]
hey 

How can I update my pod to support FA 5 ?

Please help me. 

Thanks.
