### ISSUE TITLE
Some icons do not convert to images

### ISSUE THREAD

**Issue by bitops** [thii/FontAwesome.swift#205]
This looks like the same issue as #149 -- not all icons successfully convert to images.

I am simply using the image creation code to put an image in a `UITableViewCell`, using the default style.

Code:

```swift
let image = UIImage.fontAwesomeIcon(
            name: .github,
            style: .brands,
            textColor: .black,
            size: CGSize(width: 500, height: 500)
        )

        cell?.imageView?.image = image
```

The `.github` icon works properly but none of the other icons that I've tried seem to work.

**Comment by bilawal-liaqat** [comment]
I'm getting the same issue. just Github icon working

**Comment by thii** [comment]
Could you attach a reproducible example project?

**Comment by bilawal-liaqat** [comment]
@thii  Attached screenshot and Sample Project using Pod.


[SampleFontAwesome.zip](https://github.com/thii/FontAwesome.swift/files/3240348/SampleFontAwesome.zip)
![Simulator Screen Shot - iPhone XR - 2019-05-31 at 13 01 17](https://user-images.githubusercontent.com/4446705/58690977-3cd55580-83a4-11e9-9a55-d231eecfecf9.png)

**Comment by stevewight** [comment]
@bitops @bilawal-liaqat I had the same issue and changing the ``style`` property to ``.solid`` fixed it

**Comment by bilawal-liaqat** [comment]
@stevewight changing `style` property to `.solid` github icon not working

![Screenshot 2019-06-03 at 1 26 38 PM](https://user-images.githubusercontent.com/4446705/58787431-3db7f280-8603-11e9-9ec9-47e177c1fa53.png)

**Comment by stevewight** [comment]
@bilawal-liaqat Did you try to use ``.regular`` instead of ``.solid``?  Both worked for me with ``.copyright`` and ``.volumeOff``.  The reason I believe those two do not work with ``.brands`` is because FontAwesome doesn't have a ``.brands`` version of those icons.  

The inverse is the case with the ``.github`` icon, there are no ``.regular`` or ``.solid`` versions, only ``.brands``.   I get the question mark icon when I try and use a name/style pair that doesn't exist in FontAwesome.

I found the [FontAwesome icon gallery](https://fontawesome.com/icons?d=gallery) useful.  It allows you to filter by style and see if an icon is available.

**Comment by yoiang** [comment]
It would be great if the DSL didn't allow using combinations that aren't supported.

Barring that it'd be great if `UIImage.fontAwesomeIcon` threw or notified the consumer of the API somehow, or even had a `isSupported(name:, style:)`, some way to be able to react!

**Comment by LukasHromadnik** [comment]
Yes, that would be great, but this check should be done during the compile time and not in the runtime. If you have an idea how to do it, please make a PR.

**Comment by novinfard** [comment]
@LukasHromadnik @yoiang related PR to solve the issue has been created:
https://github.com/thii/FontAwesome.swift/pull/244
