### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by RNUK** [thii/FontAwesome.swift#229]
Following Xcode update this morning. I am now getting this error when trying to compile my code. I have updated the pod repo incase there is a newer compatible version, but this hasn't fixed the issue.

Please advise.

**Comment by LukasHromadnik** [comment]
Did you use cocoapods-binary? AFAIK this error shouldn't came from pure cocoapods

**Comment by RNUK** [comment]
Yes, using cocoapods. I have cloned the repo now and manually installed. Looks like it's ok. I'll keep an eye on pod updates though

**Comment by LukasHromadnik** [comment]
This issue is related to the framework's binary which was compiled with the older version of the Xcode (here 10.3). If you are using [cocoapods-binary](https://github.com/leavez/cocoapods-binary), then you need to delete the `Pods/_Prebuild` folder and run the `pod install` command again. Otherwise I have no idea how you get this error from cocoapods
