### ISSUE TITLE
update Enum file to include pro codes

### ISSUE THREAD

**Issue by MoElnaggar14** [thii/FontAwesome.swift#267]

**Comment by MatrixSenpai** [comment]
This is going to be a no, because as open-source software we support only the open-source side. Should you need these codes, you will have to perform the following steps

- download the repository
- replace the FontAwesome submodule with the FontAwesome-Pro submodule
- run `codegen.swift`
- either manually install, or include a path entry in your Cocoapods or Carthage installation

**Comment by MoElnaggar14** [comment]
@MatrixSenpai excuse me, where can I find/ get FontAwesome-Pro submodule.

**Comment by MatrixSenpai** [comment]
You will need a license through Font Awesome, if you don't already have it. Once that's done, use their online dashboard to link your GitHub and get access to the private repository containing FontAwesome-Pro. Once that's done, add that repository as a submodule (I recommend in the FortAwesome directory) and change [this line](https://github.com/thii/FontAwesome.swift/blob/07883a32d49dfc7bdedbeea115067b53dfbeeb43/tools/main.swift#L66) to match that new submodule directory.
