### ISSUE TITLE
Font is not loaded until fontAwesomeOfSize is called

### ISSUE THREAD

**Issue by smaspe** [thii/FontAwesome.swift#55]
I have a UILabel in a Storyboard.
I set the font to FontAwesome in the storyboard.
When running the app, I set the text using `String.fontAwesomeIconWithName`, but I only see a squared ? `[?]`
However, if before that anywhere in the app I call `UIFont.fontAwesomeOfSize` (probably because it calls the FontLoader) then it work as expected.

Is there anyway to get this to work without calling `UIFont.fontAwesomeOfSize` explicitly?

**Comment by gtwilliams03** [comment]
I am having the same issue because I am trying to use emailAction.title = String.fontAwesomeIconWithName(FontAwesome.EnvelopeSquare) as an action button for an edit row in a UITableView.  Right now the icon doesn't load, and I can't find an available method to call on the button item to call UIFont.fontAwesomeOfSize.

<img width="373" alt="screenshot_2_3_16__2_02_pm" src="https://cloud.githubusercontent.com/assets/1564628/12793485/dedb560a-ca7e-11e5-8d8d-6b46504902a5.png">

**Comment by thii** [comment]
@smaspe It would be possible to make `loadFont` publicly so you can call it only once but nevertheless it's impossible to set the font in the storyboard now. If you debug it, you'll see the font will be reverted to `Helvetica` at runtime.
