### ISSUE TITLE
Doesn't work for Mac target

### ISSUE THREAD

**Issue by elsurudo** [thii/FontAwesome.swift#57]
Carthage says:
```
Dependency "FontAwesome.swift" has no shared framework schemes for any of the platforms: Mac

If you believe this to be an error, please file an issue with the maintainers at https://github.com/thii/FontAwesome.swift/issues/new
```

Looking at a bit of the source, it looks like it uses UIKit, but perhaps it is worth having this work on Mac as well. Thoughts?

**Comment by thii** [comment]
I would love to support all platforms including OS X, tvOS, and watchOS (possible?) but haven't made time for those. Pull-requests are welcome!

**Comment by Gerst20051** [comment]
What do we need to do to support Mac? @thii @elsurudo

**Comment by elsurudo** [comment]
I believe you'd need a target specific for iOS that uses and extends the UIKit classes such as UIFont, UIImage, etc. (this is what currently exists), and another target that uses and extends their AppKit counterparts (NSFont, NSImage, etc.)

And it would probably make sense to pull out the platform-independent code into somewhere separate, so it could be re-used between the two targets.

WatchOS would work the same way.

**Comment by steveatinfincia** [comment]
I [forked](https://github.com/infincia/FontAwesome.swift) and added OS X support. Have only done limited testing to ensure it actually loads and can display images, aspect/size may be off. 

Currently using` #if os()` in a few spots with partially duplicated methods. They were all tiny anyway so not such a big deal, but it still seems a crude hack :) There has to be a better way, thoughts anyone?

**Comment by thii** [comment]
@steveatinfincia Haven't try this yet but this might work maybe? Then you can use FAImage and FAFont to avoid duplicating code.

```swift
#if os(iOS) || os(watchOS) || os(tvOS)
	import UIKit
	typealias FAImage = UIImage
	typealias FAFont = UIFont
#else
	import Cocoa
	typealias FAImage = NSImage
	typealias FAFont = NSFont
#endif
```

**Comment by steveatinfincia** [comment]
@thii That's what I tried first :P

Quickly found that `NSFont` doesn't seem to have an equivalent for `UIFont.fontNamesForFamilyName()`, though I ended up removing that from the OS X method anyway so the typealias approach it may work there. Do you think the dispatch_once token by itself is enough? 

The NSImage extension needed different drawing calls, but those can probably be `#if`'d inside the method rather than duplicating it, along with another typealias for UIColor and NSColor since they're method arguments.

I will take a look at it again today and see if I can make it less crude :)

Thank you!
