### ISSUE TITLE
Hi) How to fix this code to instead of the text was an icon

### ISSUE THREAD

**Issue by Hunter-Nomad** [thii/FontAwesome.swift#91]
Hi!
How to fix this code to instead of the text was an icon?

```
@IBAction func btnApple(sender: UIButton) {
        sender.enabled = false
        sender.titleLabel?.font = UIFont.fontAwesomeOfSize(20)
        sender.titleLabel?.textColor = UIColor.blackColor()
        sender.setTitle(String.fontAwesomeIconWithName(.Apple), forState: .Normal)
}
```

Thank you)

**Comment by alexkafer** [comment]
Are you trying to make it so when a user clicks on the button (sends the IBAction), the text changes? Or just so the UIButton always has the Apple icon?

If you just want the UIButton to always use the icon, consider attaching the UIButton an IBOutlet and in the viewDidLoad use the code for the UIButton in the readme:

```
button.titleLabel?.font = UIFont.fontAwesomeOfSize(30)
button.setTitle(String.fontAwesomeIconWithName(.Github), forState: .Normal)
```

replacing button with the title you set the IBOutlet. 

Otherwise, if you want the icon to change, you'll need to be more descriptive. Are you changing from normal text to an icon? Or from one icon to another?
